### ISSUE TITLE
Create Branch with Stripped Authentication

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/node-skeleton#4]
Once everything is complete, we will create a new branch off master and remove the authentication code. This will be used in the event we don't need any user authentication.

## Steps:
- [ ] Finish:
     - [x] Authentication
     - [x] ORM/DB config
     - [x] Default Tests
     - [x] Frontend Form Validation
     - [ ] Documentation
    - [x] Clean up views
- [ ] Squash all commits in master
- [ ] Create branch `node-skeleton-stripped-auth`
- [ ] Strip user authentication code

**Comment by brandon1024** [comment]
@jacsmith21 I'd like to get your opinion on this one. What if we scrapped the idea of this? If during CEC we don't really need authentication, we could still include it as a 'wow factor'? Just an idea, would like to get your opinion.

@aeldesoky @alexodonn could you guys chip in too?

**Comment by jsmith** [comment]
Yeah I like that idea. I was thinking the same thing honestly
