### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/node-skeleton#5]
- [x] Environment Setup
- [x] Database Migrations
- [x] Technologies [in progress]
- [ ] Application and High Level Architecture Overview
- [x] Using Bookshelf.js
- [ ] Deployment
- [x] Empty Presentation [ to be stored in google drive]

**Comment by brandon1024** [comment]
Going to work on creating the Technologies doc. @aeldesoky if you could work on the presentation, that would be FAB :)

**Comment by aeldesoky** [comment]
@brandon1024 sounds good. I am just finishing some stuff for school, but I am aiming to have the presentation all good to go by Wednesday 👍

**Comment by brandon1024** [comment]
@aeldesoky how goes the presentation? I'm working on adding some documentation on our technologies used in the references-doc branch (references.md). Once i'm done that, I'm going to be available to lend a hand for refining the presentation as much as possible :)

**Comment by aeldesoky** [comment]
@brandon1024 I added more stuff to the presentation, and I think our presentation template is at a good place now. The other stuff that needs to be added are all based on the specific problem now. Let me know if you think of anything else that I should add to it.
